{
 "title": "view",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Service Latency Comparison",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(core_response_time_seconds_sum[1m])) by (action) \n  / \nsum(rate(core_response_time_seconds_count[1m])) by (action)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API Response Times",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(core_response_time_seconds_sum[1m])) / sum(rate(core_response_time_seconds_count[1m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(core_response_time_seconds_bucket[1m])) by (le))\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(core_response_time_seconds_bucket[1m])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error rates",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "100 * sum(rate(core_requests_total{http_status=~\"4..|5..\"}[1m])) \n  / sum(rate(core_requests_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Throughput – Number of requests per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(core_requests_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } }
 ]
}