global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'front'
    static_configs:
      - targets: ['front:5000']  # Container name + port

  - job_name: 'core'
    static_configs:
      - targets: ['core:5001']


